Security vulnerability
visitscotland/open-source-policy pull request #6
Opened 2024-07-08 13:44 UTC by jcalcines

2024-07-15 12:30 UTC, jameshaddrillvs approved these changes

2024-07-15 13:10 UTC, BrianGibbVS requested changes

2024-07-15 13:10 UTC, BrianGibbVS commented on SDLC_POLICIES.md
> +In VisitScotland, ensuring our software is safe and reliable is crucial. The Policy Section lays out clear guidelines for our developers or collaboratioto follow. These guidelines help us all work to
spelling...**collaboratioto**

2024-07-15 13:10 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +The purpose of this policy is to establish a standardized approach to identify, assess, and remediate code vulnerabilities in a
UK English - standardi**s**ed

2024-07-15 13:10 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +timely manner. This policy aims to protect our systems, data, and users from potential security threats while minimizing the impact on the
UK English - minimi**s**ing

2024-07-15 13:10 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +processes might be in place*
Could this be reworded, I'm not sure this is entirely true.

2024-07-15 13:10 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +- *6 months*: The current state and use of the library are not vulnerable.  However, we need to verify that we keep using the best practices.
Grammar? ....The current state and use of the library **is** not vulnerable.

2024-07-15 13:10 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +- **Iterative approach**: This policy will be defined as an iterative approach to tackle vulnerabilities. VisitScotland counts with
Reword: VisitScotland **counts** with....

2024-07-15 13:10 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +  and trying to minimize the impact in the development cycle.
Reword: and **trying** to....
UK English: minimi**s**e

2024-07-22 09:22 UTC, jcalcines commented on security/vulnerability-management.md
> +processes might be in place*
Hello Brian thank you for all the tips, I really appreciate that.

Regarding to this comment, What I tried to convey is that, we are not going to apply this timing strictly but we will introduce this in an iterative way. 

So for example, I think once we have this fully setup we will aim to deal with critical vulnerabilities within the current cycle unless it is a "major critical vulnerability" However, for Open-Source projects we might want to aim to the timelines mentioned in this section

2024-07-25 08:18 UTC, BrianGibbVS requested changes

2024-07-25 08:18 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +  will take place gradually and trying to minimise the impact in the development cycle.
"trying" should be **try**   or    reword to **will take place gradually, trying to**

2024-07-25 08:18 UTC, BrianGibbVS commented on SDLC_POLICIES.md
> +In VisitScotland, ensuring our software is safe and reliable is crucial. The Policy Section lays out clear guidelines for our developers or collaboratioto follow. These guidelines help us all work to
**collaboratioto** - what should this be?

2024-07-25 08:54 UTC, jcalcines commented on SDLC_POLICIES.md
> +In VisitScotland, ensuring our software is safe and reliable is crucial. The Policy Section lays out clear guidelines for our developers or collaboratioto follow. These guidelines help us all work to
I'm Sorry About this. 

A new feature on my IDE shows the comments in the code, and it missed some of them. I'm going through them now

2024-07-25 08:59 UTC, jcalcines commented on SDLC_POLICIES.md
> +In VisitScotland, ensuring our software is safe and reliable is crucial. The Policy Section lays out clear guidelines for our developers or collaboratioto follow. These guidelines help us all work to
It should have read "[...] for [...] collaborators to follow"

2024-07-25 09:08 UTC, BrianGibbVS approved these changes

2024-07-31 15:29 UTC, jameshaddrillvs commented on security/vulnerability-management.md
> +- **Project Managers:** Responsible for ensuring that vulnerabilities are addressed and review waivers for
Can we have a bit of clarification around this?

2024-07-31 15:32 UTC, jameshaddrillvs commented on security/vulnerability-management.md
> +- **IDE Tools**: Developer's IDE will be the first gate to identify potential vulnerabilities through static analysis
"first quality gate"?

Do we need some advice on guidance or documentation on setting this up?

2024-07-31 15:34 UTC, jameshaddrillvs commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
Is there some context missing here?

2024-08-01 07:44 UTC, allanhenderson approved these changes
Went through this with @jameshaddrillvs , with the comments addressed this is ready to go!  Thanks @jcalcines, looks great.

2024-08-01 14:48 UTC, AndyLewis1971 commented on security/vulnerability-management.md
> +6. **Verification**: The security team verifies the fix to ensure the vulnerability is effectively mitigated.
Do we need to define what the Security Team is?

2024-08-02 14:24 UTC, jcalcines commented on security/vulnerability-management.md
> +- **Project Managers:** Responsible for ensuring that vulnerabilities are addressed and review waivers for
Hi @jameshaddrillvs,

Excellent spot! It was clear on my head but obviously not in this document I will change that sentence to:

"Responsible to facilitate time for addressing the vulnerabilities, review and validate waivers are sensible or appropriate action is taken"

Does this make more sense?

2024-08-02 14:32 UTC, jcalcines commented on security/vulnerability-management.md
> +- **IDE Tools**: Developer's IDE will be the first gate to identify potential vulnerabilities through static analysis
That's a good idea but each IDE will have different tools, for example IntelliJ makes a scan while we generate code but also when we make a commit. VS COde probably works diferently. Also sometime depending on factors (time pressure, legacy code, temporal workaround, wrong suggestions, etc) we might overlook this analysis.

This might be something that fits better in Confluence rather than in our public policies

2024-08-02 14:37 UTC, jcalcines commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
Not really, It was just a confusing wording.

I have changed the wording to:
"Any waiver must be documented and approved by relevant project managers. Exceptions should only be granted if a strong justification is provided. In those cases, a waiver can be in the codebase with an expiration date and the justification"

2024-08-02 14:40 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
I thikn "relevant project managers" sounds a bit loose. Who do we explicitly mean by this?

2024-08-02 14:50 UTC, jcalcines commented on security/vulnerability-management.md
> +6. **Verification**: The security team verifies the fix to ensure the vulnerability is effectively mitigated.
@AndyLewis1971 , thank you for the comment,

The security team was a valid notion that I took from one of my readings and I missed afterward. My idea here is that we can have a second validation that doesn't come from the developer fixing the issue, just to validate that the fix is sensible for our organization.

Bear in mind that the remediation plan might not fully define how the developer will fix the issue or they might have to solve it in some other way to get this in a timely manner.

Would it work to change that paragraph to 
"The fix will be peer-reviewed by project managers and/or developers to ensure the vulnerability is effectively mitigated."

2024-08-02 14:51 UTC, allanhenderson commented on security/vulnerability-management.md
> +6. **Verification**: The security team verifies the fix to ensure the vulnerability is effectively mitigated.
I think that's a good solution @jcalcines

2024-08-02 14:59 UTC, jcalcines commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
That's correct, I was thinking on managers on different disciplines who might have a better understanding of the issue depending on how close their discipline is to the issue. But I think the word "relevant" is not required.

The point I wanted to make here is that developers must not apply waivers on their own

2024-08-02 15:06 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
Agreed.... I feel we should use the correct title for who those people who we are expecting to approve the waiver. "Project managers" could essentially mean anyone in Rachel's team, which wouldn't be right.

2024-08-05 10:14 UTC, jcalcines commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
@BrianGibbVS , That's an excellent point! I have been thinking about changing "project manager" to "technical leader" which might be a more accurate term in this policy

2024-08-05 10:39 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
Perhaps, but I still feel it is too vague. For me we should reference real people's role titles so there is accountability in the process. "Technical leader" could be anybody...

2024-08-05 11:01 UTC, jcalcines commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
I wouldn't add people's name  on this policy as it feels unnecessary changes on the policy as people move in and out of the roles. I'm not too keen to add roles names either as they might change in time but this is a good compromise so I could add this to the definition of Technical Leader?

I'm thinking on these roles:
- Digital Development Senior Manager (James)
- Digital QA & Test Senior Manager (Brian)
- Web Operations Senior Manager (Andy)
- Head of Digital Delivery (Allan)

2024-08-05 11:05 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
Indeed, we shouldn't use names on a poliocy but role / position is important. In this case, which technical leader needs to approve the waiver: Any 1 of the 4, at least 2 of the 4, all of them? What is the process we are putting in place here?

2024-08-05 11:21 UTC, jcalcines commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
I have been intentionally vague about that because on my opinion requires a bit of common sense, but I guess it is a bit subjective if we follow my approach.

My idea goes back to "_I was thinking on managers on different disciplines who might have a better understanding of the issue depending on how close their discipline is to the issue_". If a relevant manager is reached 1 approval seems ok, if a relevant manager is not available it might be up to other manager or a group decision (or even a technical delegate). 

On the other hand, I guess that we have 2 validations (developer, and senior manager) at this point and if the senior manager feels that they cannot evaluate the vulnerability, they might consult another manager. So, would it be fair to say "at least 1 approval is required"?

2024-08-05 11:39 UTC, jcalcines commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
Would it be ok to also add the following sentence "Depending on the severity of the vulnerability, more than one technical manager might need to review the waiver to validate that appropriate action and analysis has taken place"

2024-08-05 14:12 UTC, BrianGibbVS commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
Yes you're right Jose, policies should be detailed and not leave any room for subjective interpretation. That's where mistakes happen.

The example you give above could easily make up part of the policy if we agree that's the approach but we should indeed agree these things; who takes on what responsibility, in what situations are multiple resources are needed to approve a waiver? etc. This needs documented down here.

2024-08-05 15:21 UTC, allanhenderson commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
How about:

The Development Manager and Operations Manager will assess any submitted waiver requests.  Dependant on the severity of the vulnerability, one or more departmental technical experts will be invited into the approval process for accepting justification for a waiver, overseen by the Head of Department.

2024-08-08 07:21 UTC, jcalcines commented on security/vulnerability-management.md
> +In those cases, we might need to put a waiver in our code to remove that  flag
Thank you Allan, I believe that wording defines what I wanted to illustrate.

After a conversation with Brian (prior to your last comment) I was thinking on creating an independent page about waivers where we can go in depth about how to define the waivers, the systems we use and the roles included in normal situations.

2024-08-13 11:21 UTC, AndyLewis1971 approved these changes
Looks good to me Jose

2024-08-13 13:26 UTC, jameshaddrillvs approved these changes

2024-08-14 07:51 UTC, merged